//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protofiles/Mail.proto
namespace pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_UserMailInfo")]
  public partial class Mail_UserMailInfo : global::ProtoBuf.IExtensible
  {
    public Mail_UserMailInfo() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _mail_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private int _mail_type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mail_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mail_type
    {
      get { return _mail_type; }
      set { _mail_type = value; }
    }
    private int _mail_state = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mail_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mail_state
    {
      get { return _mail_state; }
      set { _mail_state = value; }
    }
    private int _mail_operate = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mail_operate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mail_operate
    {
      get { return _mail_operate; }
      set { _mail_operate = value; }
    }
    private ulong _send_time = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"send_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong send_time
    {
      get { return _send_time; }
      set { _send_time = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private int _title_id = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"title_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int title_id
    {
      get { return _title_id; }
      set { _title_id = value; }
    }
    private int _content_id = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"content_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int content_id
    {
      get { return _content_id; }
      set { _content_id = value; }
    }
    private string _items = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string items
    {
      get { return _items; }
      set { _items = value; }
    }
    private bool _is_take = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"is_take", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_take
    {
      get { return _is_take; }
      set { _is_take = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailStateType")]
    public enum MailStateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_STATE_NEW", Value=0)]
      MAIL_STATE_NEW = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_STATE_RECV_NEW", Value=1)]
      MAIL_STATE_RECV_NEW = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_STATE_HAD_READ", Value=2)]
      MAIL_STATE_HAD_READ = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_STATE_COUNT", Value=3)]
      MAIL_STATE_COUNT = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailType")]
    public enum MailType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_PLATFROM", Value=1)]
      MAIL_PLATFROM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_SYSMAIL", Value=2)]
      MAIL_SYSMAIL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_PLATFROMFIX", Value=3)]
      MAIL_PLATFROMFIX = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_PLATGIFT", Value=4)]
      MAIL_PLATGIFT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_JUST_TIPS", Value=5)]
      MAIL_JUST_TIPS = 5
    }
  
}