//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protofiles/Market.proto
namespace pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MarketBuyContent")]
  public partial class MarketBuyContent : global::ProtoBuf.IExtensible
  {
    public MarketBuyContent() {}
    
    private uint _cost_typ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cost_typ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cost_typ
    {
      get { return _cost_typ; }
      set { _cost_typ = value; }
    }
    private uint _cost_val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cost_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cost_val
    {
      get { return _cost_val; }
      set { _cost_val = value; }
    }
    private uint _give_typ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"give_typ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint give_typ
    {
      get { return _give_typ; }
      set { _give_typ = value; }
    }
    private uint _give_val;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"give_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint give_val
    {
      get { return _give_val; }
      set { _give_val = value; }
    }
    private uint _quality;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GS_Market_Buy")]
  public partial class C2GS_Market_Buy : global::ProtoBuf.IExtensible
  {
    public C2GS_Market_Buy() {}
    
    private uint _idx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint idx
    {
      get { return _idx; }
      set { _idx = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2C_Market_Buy")]
  public partial class GS2C_Market_Buy : global::ProtoBuf.IExtensible
  {
    public GS2C_Market_Buy() {}
    
    private ulong _left_num_add_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"left_num_add_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong left_num_add_time
    {
      get { return _left_num_add_time; }
      set { _left_num_add_time = value; }
    }
    private ulong _content_refresh_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"content_refresh_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong content_refresh_time
    {
      get { return _content_refresh_time; }
      set { _content_refresh_time = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.MarketBuyContent> _content = new global::System.Collections.Generic.List<pb.MarketBuyContent>();
    [global::ProtoBuf.ProtoMember(3, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.MarketBuyContent> content
    {
      get { return _content; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}